### ISSUE TITLE
CSS Upgrade

### ISSUE THREAD

**Issue by TheShonuff** [SGI-CAPP-AT2/code-highlight-n-print#13]
I can go through and update it to look a little more modern.

**Comment by SGI-CAPP-AT2** [comment]
@TheShonuff ,
Yes it's currently on decent ui,

We would like to upgrade ui but without being effected in the end product (codeblocks preview & print )

**Comment by SGI-CAPP-AT2** [comment]
@TheShonuff

**Comment by TheShonuff** [comment]
@SGI-CAPP-AT2 simple upgrade not affecting the original idea of minimalism. Added hover feature for buttons.  
![code-n-hightlight-sample](https://user-images.githubusercontent.com/24307352/195024941-344288dd-9da7-47cd-a68a-5b8a2a56c233.png)

**Comment by SGI-CAPP-AT2** [comment]
Don't change the bg of page

Restore to white

**Comment by TheShonuff** [comment]
![screen2](https://user-images.githubusercontent.com/24307352/195034153-3ad754d3-5c14-42b9-a1a7-ca9c08df3271.png)

**Comment by SGI-CAPP-AT2** [comment]
@TheShonuff ,
It's effected on the code block preview 
&
The border radii for inputs not looking good
&
The navbar looking cool but the title colors of `/` is not looking good change it to #fff
