### ISSUE TITLE
[feature] Add Multiple Fonts

### ISSUE THREAD

**Issue by anshulsoni4** [SGI-CAPP-AT2/code-highlight-n-print#4]
As you can see this project is for code highlighting and printing
So we need to have fonts related to code

But I also want this project have multiple fonts

So the tasklist for you is
- [x] create classes in `css` with names `montserrat` & `default`
- [x] create toggle for them with `select` tag 
- [x] store the value of  select in localstorage
- [x] Add the class stored in local storage

> Create fonts.js for handling all the tasks

ShGI

**Comment by SGI-CAPP-AT2** [comment]
@anshulsoni4
Let me know the font details
I'll assign you after reviewing font details

**Comment by anshulsoni4** [comment]
ok no problem @SGI-CAPP-AT2

**Comment by SGI-CAPP-AT2** [comment]
@anshulsoni4 any updates about fonts

**Comment by anshulsoni4** [comment]
should i update them @SGI-CAPP-AT2 ?

**Comment by SGI-CAPP-AT2** [comment]
> should i update them @SGI-CAPP-AT2 ?

First let me know font name (family)

**Comment by anshulsoni4** [comment]
Montserrat it is @SGI-CAPP-AT2

**Comment by SGI-CAPP-AT2** [comment]
@anshulsoni4 

As you can see this project is for code highlighting and printing
So we need to have fonts related to code

But I also want this project have multiple fonts

So the tasklist for you is
- [ ] create classes in `css` with names `montserrat` & `default`
- [ ] create toggle for them with `select` tag 
- [ ] store the value of  select in localstorage
- [ ] set localstorage Val to the class to body

> Create fonts.js for handling all the tasks


ShGI

**Comment by aparna03dubey** [comment]
May I update them please? @SGI-CAPP-AT2

**Comment by SGI-CAPP-AT2** [comment]
@aparna03dubey 
> May I update them please? @SGI-CAPP-AT2

Yep ,
Not just updating fonts
You've to do that all tasks

_ShGI_

**Comment by SGI-CAPP-AT2** [comment]
fixed by https://github.com/SGI-CAPP-AT2/code-highlight-n-print/commit/2191f9dafb0615d84129aac1e7d7b799d13e1aeb

**Comment by anshulsoni4** [comment]
Alright
