### ISSUE TITLE
Adding contributing.md file 

### ISSUE THREAD

**Issue by anshulsoni4** [SGI-CAPP-AT2/code-highlight-n-print#5]
A contributing.md file is a must for all projects so that we can know the Prerequisite, and how to contribute to the project.

**Comment by SGI-CAPP-AT2** [comment]
@anshulsoni4 issue is assigned to you .
- [x] create contributing.md

**Comment by anshulsoni4** [comment]
Thankyou @SGI-CAPP-AT2

**Comment by SGI-CAPP-AT2** [comment]
fixed by #6
