### ISSUE TITLE
[DOCS] Edit `guide.md` with new feature

### ISSUE THREAD

**Issue by SGI-CAPP-AT2** [SGI-CAPP-AT2/code-highlight-n-print#8]
- [ ] Take a tour of [tool](https://sgi-capp-at2.github.io/code-highlight-n-print/tool/)
- [ ] Add/Update the feature information inside [`guide.md`](https://github.com/SGI-CAPP-AT2/code-highlight-n-print/blob/main/guide.md)

**Comment by ErebusXAbyss** [comment]
I would like to work on this issue.

**Comment by SGI-CAPP-AT2** [comment]
> I would like to work on this issue.

Go ahead

**Comment by SGI-CAPP-AT2** [comment]
@all-contributors please add @jakebolam for infrastructure, tests and code

**Comment by SGI-CAPP-AT2** [comment]
@all-contributors please add @SGI-CAPP-AT2  for infrastructure, tests and code

**Comment by SGI-CAPP-AT2** [comment]
@all-contributors please remove @jakebolam for infrastructure, tests and code

**Comment by SGI-CAPP-AT2** [comment]
@all-contributors please add @SGI-CAPP-AT2  for infrastructure, tests and code

**Comment by SGI-CAPP-AT2** [comment]
@ErebusXAbyss any updates

**Comment by ErebusXAbyss** [comment]
Yes sir, updating the feature information inside guide.md (adding multiple fonts section)

**Comment by SGI-CAPP-AT2** [comment]
Closed as no reply from anyone
